import type { Artist, Attendance, ConcertJourney } from './types';

export const artists: Record<string, Artist> = {
  riize: {
    id: 'artist-riize',
    name: 'RIIZE',
    koreanName: '라이즈',
    agency: 'SM Entertainment',
    accent: '#826EFF',
  },
  seventeen: {
    id: 'artist-seventeen',
    name: 'SEVENTEEN',
    koreanName: '세븐틴',
    agency: 'PLEDIS Entertainment',
    accent: '#F0B45E',
  },
  aespa: {
    id: 'artist-aespa',
    name: 'aespa',
    koreanName: '에스파',
    agency: 'SM Entertainment',
    accent: '#62E6D8',
  },
  ive: {
    id: 'artist-ive',
    name: 'IVE',
    koreanName: '아이브',
    agency: 'Starship Entertainment',
    accent: '#FF6F91',
  },
};

export const demoJourneys: ConcertJourney[] = [
  {
    id: 'journey-riize-hong-kong',
    slug: 'riize-hong-kong',
    artist: artists.riize,
    tourName: 'RIIZING LOUD',
    venue: {
      id: 'venue-asiaworld-arena',
      name: 'AsiaWorld–Arena',
      city: 'Hong Kong',
      market: 'HK',
      timezone: 'Asia/Hong_Kong',
      latitude: 22.3214,
      longitude: 113.9433,
    },
    performanceStartsAt: '2026-12-14T20:00:00+08:00',
    milestones: [
      {
        id: 'riize-hkg-membership',
        type: 'membership',
        title: 'Confirm BRIIZE membership',
        description: 'Membership must be active before registration.',
        startsAt: '2026-08-10T12:00:00+08:00',
        endsAt: '2026-08-15T23:59:00+08:00',
        timezone: 'Asia/Hong_Kong',
        state: 'completed',
        sourceIds: ['weverse-riize'],
      },
      {
        id: 'riize-hkg-registration',
        type: 'registration',
        title: 'Complete presale registration',
        description: 'Register the membership for the Hong Kong date.',
        startsAt: '2026-08-20T12:00:00+08:00',
        endsAt: '2026-08-22T23:59:00+08:00',
        timezone: 'Asia/Hong_Kong',
        state: 'active',
        requires: ['riize-hkg-membership'],
        sourceIds: ['weverse-riize', 'ticketmaster-sg'],
        actionUrl: 'https://weverse.io/riize/notice',
      },
      {
        id: 'riize-hkg-presale',
        type: 'presale',
        title: 'Membership presale',
        description: 'Use the membership number as the access credential.',
        startsAt: '2026-08-26T12:00:00+08:00',
        endsAt: '2026-08-26T23:59:00+08:00',
        timezone: 'Asia/Hong_Kong',
        state: 'upcoming',
        requires: ['riize-hkg-registration'],
        sourceIds: ['ticketmaster-sg'],
      },
      {
        id: 'riize-hkg-general',
        type: 'general_sale',
        title: 'General sale',
        description: 'Public sale through the verified official seller.',
        startsAt: '2026-08-28T10:00:00+08:00',
        timezone: 'Asia/Hong_Kong',
        state: 'upcoming',
        sourceIds: ['ticketmaster-sg'],
      },
      {
        id: 'riize-hkg-ticket',
        type: 'ticket_delivery',
        title: 'Ticket delivery check',
        description: 'Confirm delivery method and entry requirements.',
        startsAt: '2026-12-10T10:00:00+08:00',
        timezone: 'Asia/Hong_Kong',
        state: 'upcoming',
        sourceIds: ['ticketmaster-sg'],
      },
      {
        id: 'riize-hkg-show',
        type: 'show',
        title: 'Show time',
        description: 'Venue-local performance time.',
        startsAt: '2026-12-14T20:00:00+08:00',
        timezone: 'Asia/Hong_Kong',
        state: 'upcoming',
        sourceIds: ['ticketmaster-sg'],
      },
    ],
    sources: [
      {
        id: 'weverse-riize',
        name: 'Weverse · RIIZE notices',
        url: 'https://weverse.io/riize/notice',
        host: 'weverse.io',
        confidence: 'official',
        checkedAt: '2026-08-22T11:34:00+08:00',
      },
      {
        id: 'ticketmaster-sg',
        name: 'Ticketmaster Singapore',
        url: 'https://ticketmaster.sg/',
        host: 'ticketmaster.sg',
        confidence: 'official',
        checkedAt: '2026-08-22T11:36:00+08:00',
      },
    ],
    officialSeller: 'Ticketmaster',
    officialSellerHost: 'ticketmaster.sg',
    ticketLimit: 4,
    travelDistanceKm: 2589,
    demo: true,
  },
  {
    id: 'journey-seventeen-singapore',
    slug: 'seventeen-singapore',
    artist: artists.seventeen,
    tourName: 'NEW HORIZON',
    venue: {
      id: 'venue-national-stadium-sg',
      name: 'National Stadium',
      city: 'Singapore',
      market: 'SG',
      timezone: 'Asia/Singapore',
      latitude: 1.3043,
      longitude: 103.8742,
    },
    performanceStartsAt: '2026-12-19T19:30:00+08:00',
    milestones: [
      {
        id: 'svt-sg-registration',
        type: 'registration',
        title: 'CARAT presale registration closes',
        description: 'City-specific membership registration.',
        startsAt: '2026-08-27T11:00:00+08:00',
        endsAt: '2026-09-02T22:59:00+08:00',
        timezone: 'Asia/Singapore',
        state: 'upcoming',
        sourceIds: ['weverse-seventeen'],
      },
      {
        id: 'svt-sg-presale',
        type: 'presale',
        title: 'CARAT membership presale',
        description: 'Access code required.',
        startsAt: '2026-09-08T10:00:00+08:00',
        timezone: 'Asia/Singapore',
        state: 'upcoming',
        sourceIds: ['ticketmaster-sg'],
      },
      {
        id: 'svt-sg-show',
        type: 'show',
        title: 'Show time',
        description: 'Venue-local performance time.',
        startsAt: '2026-12-19T19:30:00+08:00',
        timezone: 'Asia/Singapore',
        state: 'upcoming',
        sourceIds: ['ticketmaster-sg'],
      },
    ],
    sources: [
      {
        id: 'weverse-seventeen',
        name: 'Weverse · SEVENTEEN notices',
        url: 'https://weverse.io/seventeen/notice',
        host: 'weverse.io',
        confidence: 'official',
        checkedAt: '2026-08-22T10:42:00+08:00',
      },
      {
        id: 'ticketmaster-sg',
        name: 'Ticketmaster Singapore',
        url: 'https://ticketmaster.sg/',
        host: 'ticketmaster.sg',
        confidence: 'official',
        checkedAt: '2026-08-22T10:47:00+08:00',
      },
    ],
    officialSeller: 'Ticketmaster Singapore',
    officialSellerHost: 'ticketmaster.sg',
    ticketLimit: 4,
    demo: true,
  },
  {
    id: 'journey-aespa-bangkok',
    slug: 'aespa-bangkok',
    artist: artists.aespa,
    tourName: 'SYNK : PARALLEL LINE',
    venue: {
      id: 'venue-impact-arena',
      name: 'IMPACT Arena',
      city: 'Bangkok',
      market: 'TH',
      timezone: 'Asia/Bangkok',
      latitude: 13.9126,
      longitude: 100.5478,
    },
    performanceStartsAt: '2026-11-07T19:00:00+07:00',
    milestones: [
      {
        id: 'aespa-bkk-general',
        type: 'general_sale',
        title: 'General sale',
        description: 'Public sale on the official ticketing platform.',
        startsAt: '2026-09-11T10:00:00+07:00',
        timezone: 'Asia/Bangkok',
        state: 'upcoming',
        sourceIds: ['thaiticketmajor'],
      },
      {
        id: 'aespa-bkk-show',
        type: 'show',
        title: 'Show time',
        description: 'Venue-local performance time.',
        startsAt: '2026-11-07T19:00:00+07:00',
        timezone: 'Asia/Bangkok',
        state: 'upcoming',
        sourceIds: ['thaiticketmajor'],
      },
    ],
    sources: [
      {
        id: 'thaiticketmajor',
        name: 'ThaiTicketMajor',
        url: 'https://www.thaiticketmajor.com/',
        host: 'thaiticketmajor.com',
        confidence: 'official',
        checkedAt: '2026-08-22T09:18:00+07:00',
      },
    ],
    officialSeller: 'ThaiTicketMajor',
    officialSellerHost: 'thaiticketmajor.com',
    ticketLimit: 4,
    travelDistanceKm: 1429,
    demo: true,
  },
  {
    id: 'journey-ive-taipei',
    slug: 'ive-taipei',
    artist: artists.ive,
    tourName: 'SHOW WHAT I HAVE',
    venue: {
      id: 'venue-taipei-arena',
      name: 'Taipei Arena',
      city: 'Taipei',
      market: 'TW',
      timezone: 'Asia/Taipei',
      latitude: 25.0514,
      longitude: 121.5497,
    },
    performanceStartsAt: '2026-10-24T19:00:00+08:00',
    milestones: [
      {
        id: 'ive-tpe-sale',
        type: 'general_sale',
        title: 'General sale',
        description: 'Official public on-sale.',
        startsAt: '2026-09-18T12:00:00+08:00',
        timezone: 'Asia/Taipei',
        state: 'upcoming',
        sourceIds: ['tixcraft'],
      },
      {
        id: 'ive-tpe-show',
        type: 'show',
        title: 'Show time',
        description: 'Venue-local performance time.',
        startsAt: '2026-10-24T19:00:00+08:00',
        timezone: 'Asia/Taipei',
        state: 'upcoming',
        sourceIds: ['tixcraft'],
      },
    ],
    sources: [
      {
        id: 'tixcraft',
        name: 'tixCraft',
        url: 'https://tixcraft.com/',
        host: 'tixcraft.com',
        confidence: 'official',
        checkedAt: '2026-08-22T10:02:00+08:00',
      },
    ],
    officialSeller: 'tixCraft',
    officialSellerHost: 'tixcraft.com',
    ticketLimit: 4,
    travelDistanceKm: 3220,
    demo: true,
  },
];

export const demoAttendances: Attendance[] = [
  {
    id: 'attendance-riize-seoul-2025',
    artist: artists.riize,
    city: 'Seoul',
    market: 'KR',
    venue: 'KSPO Dome',
    attendedAt: '2025-06-21T19:00:00+09:00',
    travelDistanceKm: 4667,
    verification: 'ticket_import',
    accent: '#826EFF',
  },
  {
    id: 'attendance-svt-hkg-2025',
    artist: artists.seventeen,
    city: 'Hong Kong',
    market: 'HK',
    venue: 'AsiaWorld–Arena',
    attendedAt: '2025-01-19T19:00:00+08:00',
    travelDistanceKm: 2589,
    verification: 'ticket_import',
    accent: '#F0B45E',
  },
  {
    id: 'attendance-aespa-bkk-2024',
    artist: artists.aespa,
    city: 'Bangkok',
    market: 'TH',
    venue: 'IMPACT Arena',
    attendedAt: '2024-09-29T19:00:00+07:00',
    travelDistanceKm: 1429,
    verification: 'self_attested',
    accent: '#62E6D8',
  },
  {
    id: 'attendance-ive-sg-2024',
    artist: artists.ive,
    city: 'Singapore',
    market: 'SG',
    venue: 'Singapore Indoor Stadium',
    attendedAt: '2024-02-24T19:00:00+08:00',
    travelDistanceKm: 18,
    verification: 'location_confirmed',
    accent: '#FF6F91',
  },
];

export function getJourneyBySlug(slug: string): ConcertJourney | undefined {
  return demoJourneys.find((journey) => journey.slug === slug);
}
