import type { SourceChannel } from '@/lib/domain/types';

export const sourceRegistry: SourceChannel[] = [
  {
    id: 'the-star-sg', name: 'The Star Performing Arts Centre', category: 'venue',
    markets: ['SG'], url: 'https://www.thestar.sg/events', host: 'thestar.sg',
    status: 'verified_link', tier: 1, capabilities: ['announce'],
    notes: 'Official venue schedule; public HTML, no API key. Single-performance dates only; unfamiliar artists stay in review.',
  },
  {
    id: 'weverse',
    name: 'Weverse Notices',
    category: 'fan_platform',
    markets: ['SG', 'HK', 'JP', 'TW', 'TH', 'KR', 'MY', 'PH', 'ID', 'VN'],
    url: 'https://weverse.io/',
    host: 'weverse.io',
    status: 'verified_link',
    tier: 1,
    capabilities: ['announce', 'registration', 'identity'],
    notes: 'Primary source for membership eligibility and city-specific presale registration.',
  },
  {
    id: 'bstage',
    name: 'b.stage',
    category: 'fan_platform',
    markets: ['SG', 'HK', 'JP', 'TW', 'TH', 'KR'],
    url: 'https://www.bstage.in/',
    host: 'bstage.in',
    status: 'verified_link',
    tier: 1,
    capabilities: ['announce', 'registration', 'identity'],
    notes: 'Official membership and fan-club notices for participating artists.',
  },
  {
    id: 'ticketmaster-discovery',
    name: 'Ticketmaster Discovery API',
    category: 'event_api',
    markets: ['SG', 'HK', 'AU', 'NZ'],
    url: 'https://developer.ticketmaster.com/products-and-docs/apis/discovery-api/v2/',
    host: 'developer.ticketmaster.com',
    status: 'key_required',
    tier: 1,
    capabilities: ['announce', 'sale', 'purchase'],
    notes: 'Live adapter included. Coverage varies by country and commercial availability.',
  },
  {
    id: 'predicthq',
    name: 'PredictHQ Events API',
    category: 'event_api',
    markets: ['SG', 'HK', 'JP', 'TW', 'TH', 'KR', 'MY', 'PH', 'ID', 'VN', 'AU', 'NZ'],
    url: 'https://docs.predicthq.com/api/events/search-events',
    host: 'api.predicthq.com',
    status: 'key_required',
    tier: 2,
    capabilities: ['announce'],
    notes: 'Broad discovery supplement; official ticket milestones still require primary sources.',
  },
  {
    id: 'musicbrainz',
    name: 'MusicBrainz',
    category: 'artist_identity',
    markets: ['SG', 'HK', 'JP', 'TW', 'TH', 'KR', 'MY', 'PH', 'ID', 'VN', 'AU', 'NZ'],
    url: 'https://musicbrainz.org/doc/MusicBrainz_API',
    host: 'musicbrainz.org',
    status: 'verified_link',
    tier: 2,
    capabilities: ['identity'],
    notes: 'Canonical artist identity and aliases; never treated as a ticket deadline source.',
  },
  {
    id: 'wikidata',
    name: 'Wikidata Query Service',
    category: 'artist_identity',
    markets: ['SG', 'HK', 'JP', 'TW', 'TH', 'KR', 'MY', 'PH', 'ID', 'VN', 'AU', 'NZ'],
    url: 'https://query.wikidata.org/',
    host: 'query.wikidata.org',
    status: 'live',
    tier: 2,
    capabilities: ['identity'],
    notes: 'Machine-readable K-pop genre, group identity and inception evidence used to discover newly debuted acts.',
  },
  {
    id: 'ticket-pia-jp',
    name: 'Ticket PIA Japan',
    category: 'ticketing',
    markets: ['JP'],
    url: 'https://t.pia.jp/en/',
    host: 't.pia.jp',
    status: 'verified_link',
    tier: 1,
    capabilities: ['registration', 'lottery', 'sale', 'purchase'],
    notes: 'Major Japan primary seller; account, phone, payment, and pickup eligibility vary by event.',
  },
  {
    id: 'eplus-jp',
    name: 'e+ Japan',
    category: 'ticketing',
    markets: ['JP'],
    url: 'https://eplus.jp/sf/live/k-pop-asian',
    host: 'eplus.jp',
    status: 'verified_link',
    tier: 1,
    capabilities: ['registration', 'lottery', 'sale', 'purchase'],
    notes: 'Major Japan seller with a dedicated K-pop and Asian live catalog; eligibility is event-specific.',
  },
  {
    id: 'lawson-ticket-jp',
    name: 'Lawson Ticket Japan',
    category: 'ticketing',
    markets: ['JP'],
    url: 'https://l-tike.com/concert/',
    host: 'l-tike.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['registration', 'lottery', 'sale', 'purchase'],
    notes: 'Major Japan primary seller; models first-come, lottery, payment, and delivery as separate milestones.',
  },
  {
    id: 'ticketmaster-sg',
    name: 'Ticketmaster Singapore',
    category: 'ticketing',
    markets: ['SG'],
    url: 'https://ticketmaster.sg/',
    host: 'ticketmaster.sg',
    status: 'verified_link',
    tier: 1,
    capabilities: ['registration', 'sale', 'purchase'],
    notes: 'Official seller. Event links are verified automatically; checkout remains on the seller domain.',
  },
  {
    id: 'sistic',
    name: 'SISTIC',
    category: 'ticketing',
    markets: ['SG'],
    url: 'https://www.sistic.com.sg/',
    host: 'sistic.com.sg',
    status: 'verified_link',
    tier: 1,
    capabilities: ['sale', 'purchase'],
    notes: 'Major Singapore primary ticket seller.',
  },
  {
    id: 'bookmyshow-sg',
    name: 'BookMyShow Singapore',
    category: 'ticketing',
    markets: ['SG'],
    url: 'https://sg.bookmyshow.com/',
    host: 'sg.bookmyshow.com',
    status: 'verified_link',
    tier: 2,
    capabilities: ['sale', 'purchase'],
    notes: 'Supplementary Singapore primary seller coverage.',
  },
  {
    id: 'hkticketing',
    name: 'HK Ticketing',
    category: 'ticketing',
    markets: ['HK'],
    url: 'https://www.hkticketing.com/',
    host: 'hkticketing.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['registration', 'sale', 'purchase'],
    notes: 'Core Hong Kong official ticket channel.',
  },
  {
    id: 'cityline',
    name: 'Cityline',
    category: 'ticketing',
    markets: ['HK'],
    url: 'https://www.cityline.com/',
    host: 'cityline.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['sale', 'purchase'],
    notes: 'Core Hong Kong official ticket channel.',
  },
  {
    id: 'kktix',
    name: 'KKTIX',
    category: 'ticketing',
    markets: ['HK', 'TW'],
    url: 'https://kktix.com/',
    host: 'kktix.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['registration', 'sale', 'purchase'],
    notes: 'Important Hong Kong and Taiwan seller for concerts and fan events.',
  },
  {
    id: 'tixcraft',
    name: 'tixCraft',
    category: 'ticketing',
    markets: ['TW'],
    url: 'https://tixcraft.com/',
    host: 'tixcraft.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['sale', 'purchase'],
    notes: 'Core Taiwan primary ticket channel.',
  },
  {
    id: 'ibon',
    name: 'ibon Tickets',
    category: 'ticketing',
    markets: ['TW'],
    url: 'https://ticket.ibon.com.tw/',
    host: 'ticket.ibon.com.tw',
    status: 'verified_link',
    tier: 2,
    capabilities: ['sale', 'purchase'],
    notes: 'Taiwan seller and convenience-store fulfillment channel.',
  },
  {
    id: 'famiticket',
    name: 'FamiTicket',
    category: 'ticketing',
    markets: ['TW'],
    url: 'https://www.famiticket.com.tw/',
    host: 'famiticket.com.tw',
    status: 'verified_link',
    tier: 2,
    capabilities: ['sale', 'purchase'],
    notes: 'Taiwan seller and FamilyMart fulfillment channel.',
  },
  {
    id: 'thaiticketmajor',
    name: 'ThaiTicketMajor',
    category: 'ticketing',
    markets: ['TH'],
    url: 'https://www.thaiticketmajor.com/',
    host: 'thaiticketmajor.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['registration', 'sale', 'purchase'],
    notes: 'Core Thailand primary ticket channel.',
  },
  {
    id: 'allticket',
    name: 'AllTicket',
    category: 'ticketing',
    markets: ['TH'],
    url: 'https://www.allticket.com/',
    host: 'allticket.com',
    status: 'verified_link',
    tier: 2,
    capabilities: ['sale', 'purchase'],
    notes: 'Thailand ticketing and retail fulfillment coverage.',
  },
  {
    id: 'global-interpark',
    name: 'NOL Ticket / Global Interpark',
    category: 'ticketing',
    markets: ['KR'],
    url: 'https://www.globalinterpark.com/en/category-list/concert',
    host: 'globalinterpark.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['registration', 'lottery', 'sale', 'purchase'],
    notes: 'Major Korea ticket channel with a global-facing purchase surface.',
  },
  {
    id: 'melon-ticket',
    name: 'Melon Ticket',
    category: 'ticketing',
    markets: ['KR'],
    url: 'https://ticket.melon.com/',
    host: 'ticket.melon.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['registration', 'sale', 'purchase'],
    notes: 'Major Korea ticketing platform.',
  },
  {
    id: 'ticketlink-kr',
    name: 'Ticketlink Korea',
    category: 'ticketing',
    markets: ['KR'],
    url: 'https://www.ticketlink.co.kr/',
    host: 'ticketlink.co.kr',
    status: 'verified_link',
    tier: 2,
    capabilities: ['sale', 'purchase'],
    notes: 'Korea primary ticket channel.',
  },
  {
    id: 'sm-tickets',
    name: 'SM Tickets',
    category: 'ticketing',
    markets: ['PH'],
    url: 'https://smtickets.com/',
    host: 'smtickets.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['sale', 'purchase'],
    notes: 'Core Philippines concert ticket channel.',
  },
  {
    id: 'ticketnet-ph',
    name: 'TicketNet Philippines',
    category: 'ticketing',
    markets: ['PH'],
    url: 'https://www.ticketnet.com.ph/',
    host: 'ticketnet.com.ph',
    status: 'verified_link',
    tier: 2,
    capabilities: ['sale', 'purchase'],
    notes: 'Philippines primary ticket channel.',
  },
  {
    id: 'ticket2u',
    name: 'Ticket2U',
    category: 'ticketing',
    markets: ['MY'],
    url: 'https://www.ticket2u.com.my/',
    host: 'ticket2u.com.my',
    status: 'verified_link',
    tier: 2,
    capabilities: ['sale', 'purchase'],
    notes: 'Malaysia event and ticket platform.',
  },
  {
    id: 'golive-my',
    name: 'GoLive Asia',
    category: 'ticketing',
    markets: ['MY'],
    url: 'https://www.golive-asia.com/',
    host: 'golive-asia.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['registration', 'sale', 'purchase'],
    notes: 'Authorized primary seller for selected major Kuala Lumpur K-pop tours; authority remains event-specific.',
  },
  {
    id: 'bookmyshow-my',
    name: 'BookMyShow Malaysia',
    category: 'ticketing',
    markets: ['MY'],
    url: 'https://my.bookmyshow.com/',
    host: 'my.bookmyshow.com',
    status: 'verified_link',
    tier: 2,
    capabilities: ['sale', 'purchase'],
    notes: 'Supplementary Malaysia primary ticketing coverage.',
  },
  {
    id: 'loket-id',
    name: 'LOKET',
    category: 'ticketing',
    markets: ['ID'],
    url: 'https://www.loket.com/',
    host: 'loket.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['sale', 'purchase'],
    notes: 'Core Indonesia primary event ticket channel.',
  },
  {
    id: 'tiket-id',
    name: 'tiket.com To Do',
    category: 'ticketing',
    markets: ['ID'],
    url: 'https://www.tiket.com/to-do',
    host: 'tiket.com',
    status: 'verified_link',
    tier: 2,
    capabilities: ['sale', 'purchase'],
    notes: 'Authorized seller for selected Indonesia concerts; verify against the event promoter before surfacing.',
  },
  {
    id: 'ticketbox-vn',
    name: 'Ticketbox Vietnam',
    category: 'ticketing',
    markets: ['VN'],
    url: 'https://ticketbox.vn/',
    host: 'ticketbox.vn',
    status: 'verified_link',
    tier: 1,
    capabilities: ['sale', 'purchase'],
    notes: 'Core Vietnam event ticket channel, including selected Korean artist events.',
  },
  {
    id: 'ticketmaster-au',
    name: 'Ticketmaster Australia',
    category: 'ticketing',
    markets: ['AU'],
    url: 'https://www.ticketmaster.com.au/',
    host: 'ticketmaster.com.au',
    status: 'verified_link',
    tier: 1,
    capabilities: ['sale', 'inventory', 'purchase'],
    notes: 'Australia primary seller with Discovery API coverage for many events.',
  },
  {
    id: 'ticketek-au',
    name: 'Ticketek Australia',
    category: 'ticketing',
    markets: ['AU'],
    url: 'https://premier.ticketek.com.au/',
    host: 'premier.ticketek.com.au',
    status: 'verified_link',
    tier: 1,
    capabilities: ['sale', 'purchase'],
    notes: 'Australia primary ticket channel.',
  },
  {
    id: 'ticketmaster-nz',
    name: 'Ticketmaster New Zealand',
    category: 'ticketing',
    markets: ['NZ'],
    url: 'https://www.ticketmaster.co.nz/',
    host: 'ticketmaster.co.nz',
    status: 'verified_link',
    tier: 1,
    capabilities: ['sale', 'inventory', 'purchase'],
    notes: 'New Zealand primary seller with Discovery API coverage for many events.',
  },
  {
    id: 'livenation-my',
    name: 'Live Nation Malaysia',
    category: 'promoter',
    markets: ['MY'],
    url: 'https://www.livenation.my/',
    host: 'livenation.my',
    status: 'verified_link',
    tier: 1,
    capabilities: ['announce', 'registration', 'sale'],
    notes: 'Official promoter source; its event page identifies the authorized seller for each show.',
  },
  {
    id: 'mecimapro-id',
    name: 'Mecimapro Indonesia',
    category: 'promoter',
    markets: ['ID'],
    url: 'https://www.mecimapro.com/',
    host: 'mecimapro.com',
    status: 'verified_link',
    tier: 1,
    capabilities: ['announce', 'registration', 'sale'],
    notes: 'Korean concert and fan-event promoter; use its event notice to validate the authorized ticket host.',
  },
  {
    id: 'livenation-sg',
    name: 'Live Nation Singapore',
    category: 'promoter',
    markets: ['SG'],
    url: 'https://www.livenation.sg/',
    host: 'livenation.sg',
    status: 'verified_link',
    tier: 1,
    capabilities: ['announce', 'registration', 'sale'],
    notes: 'Official promoter announcements and presale windows.',
  },
  {
    id: 'livenation-hk',
    name: 'Live Nation Hong Kong',
    category: 'promoter',
    markets: ['HK'],
    url: 'https://www.livenation.hk/',
    host: 'livenation.hk',
    status: 'verified_link',
    tier: 1,
    capabilities: ['announce', 'registration', 'sale'],
    notes: 'Official Hong Kong promoter announcements and presales.',
  },
  {
    id: 'livenation-tw',
    name: 'Live Nation Taiwan',
    category: 'promoter',
    markets: ['TW'],
    url: 'https://www.livenation.com.tw/',
    host: 'livenation.com.tw',
    status: 'verified_link',
    tier: 1,
    capabilities: ['announce', 'registration', 'sale'],
    notes: 'Official Taiwan promoter announcements and presales.',
  },
  {
    id: 'livenation-tero',
    name: 'Live Nation Tero',
    category: 'promoter',
    markets: ['TH'],
    url: 'https://www.livenationtero.co.th/',
    host: 'livenationtero.co.th',
    status: 'verified_link',
    tier: 1,
    capabilities: ['announce', 'registration', 'sale'],
    notes: 'Official Thailand promoter announcements and presales.',
  },
  {
    id: 'livenation-ph',
    name: 'Live Nation Philippines',
    category: 'promoter',
    markets: ['PH'],
    url: 'https://www.livenation.ph/',
    host: 'livenation.ph',
    status: 'verified_link',
    tier: 1,
    capabilities: ['announce', 'registration', 'sale'],
    notes: 'Official Philippines promoter announcements and presales.',
  },
  {
    id: 'livenation-jp', name: 'Live Nation H.I.P. Japan', category: 'promoter', markets: ['JP'],
    url: 'https://www.livenationhip.co.jp/', host: 'livenationhip.co.jp', status: 'verified_link', tier: 1,
    capabilities: ['announce', 'sale'], notes: 'Official Japan promoter calendar; independently checked public pages.',
  },
  {
    id: 'livenation-kr',
    name: 'Live Nation Korea',
    category: 'promoter',
    markets: ['KR'],
    url: 'https://www.livenation.kr/',
    host: 'livenation.kr',
    status: 'verified_link',
    tier: 1,
    capabilities: ['announce', 'registration', 'sale'],
    notes: 'Official Korea promoter announcements and presales.',
  },
];

const officialHosts = new Set(sourceRegistry.map((source) => source.host));

export function isVerifiedOfficialHost(host: string): boolean {
  const normalized = host.toLowerCase().replace(/^www\./, '');
  return [...officialHosts].some((candidate) => {
    const normalizedCandidate = candidate.toLowerCase().replace(/^www\./, '');
    return normalized === normalizedCandidate || normalized.endsWith(`.${normalizedCandidate}`);
  });
}

export function getSourcesForMarket(market: string): SourceChannel[] {
  return sourceRegistry.filter((source) => source.markets.includes(market as never));
}
